language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hegeda/mesterlogika-1.0 .

before_deploy:
  - rvm 2.4.5 do gem install aws-sdk -v 2.11.536

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "mesterklogika"
  env: "Mesterklogika-env"
  bucket_name: "elasticbeanstalk-us-east-2-709699025531"
  bucket_path: "mesterklogika"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
