language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hegeda/mesterlogika-1.0 .

script:
  - docker run hegeda/mesterlogika-1.0 -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "mesterklogika"
  env: "Mesterklogika-env"
  bucket_name: "elasticbeanstalk-us-east-2-709699025531"
  bucket_path: "mesterklogika"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
