# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - hegeapp01

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_e6d71fb04ac64e9fae04c231923530c0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9a1a32868bdc4b12a0bb754d9d6053ad }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_e6d71fb04ac64e9fae04c231923530c0 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hegeapp01'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_68251249c8ac47059d8cad659bff0a1f }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_e6d71fb04ac64e9fae04c231923530c0 }}/appsvc/staticsite:${{ github.sha }}'